package com.security.controller;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class HomeController {
	
	//default ----Username as ---> user
	//default ----Password ------> autogenerated password

	@GetMapping("/")
	public String homePage() {
		return "index";
	}
	
	@GetMapping("/user")
	public String userPage() {
		return "user";
	}
	
	@GetMapping("/admin")
	public String adminPage() {
		return "admin";
	}
}
